### ISSUE TITLE
Setting bacularis.users htpasswd file is not read until user is edited in "Basic users"  panel.

### ISSUE THREAD

**Issue by howels** [bacularis/bacularis-api#6]
I have repeatedly re-installed Bacularis and cannot input a password for the API users prior to install. Appears that the presence of a password for the default admin user is only acknowledged after an attempt is made to set the password via the web panel, either via the Configuration Wizard or Basic users panel item.

Is there a way to read in a pre-existing htpasswd file for the Bacularis API?

Observed in Bacularis 2.3.0 on Debian 11

**Comment by howels** [comment]
Looks like `fatrace` found the answer - API/basic.conf needs an entry for that user too.

**Comment by ganiuszka** [comment]
Hello @howels

Thank you for opening this issue.

I think that you are not able to use API users because in the Bacularis API we have two type of resources:

 - access to the web panel to manage the API,
 - access to the Bacula resources trought the API endpoints.

For the first point, setting user and password in the ``bacularis.users`` file is sufficient. You are able to log in to the panel and manage it.

For the second point, access to the Bacula resources needs a something like the Bacularis API user account. In this user access the user is defined if he/she uses dedicated Bacula Console ACLs to restrict resources or he/she is unlimitted access user.

For your pre-defiend API users I would propose to create the following file:

```
[BACULARIS_DIR]/protected/API/Config/basic.conf
```

and define inside it all the API users (that you have in the ``bacularis.users``) in a form (example for ``user123`` and ``user456``):

```
[user123]
bconsole_cfg_path = ""

[user456]
bconsole_cfg_path = ""
```

In one of these users should use the dedicated Bacula Console, you can define this dedicated Bconsole file in the ``bconsole_cfg_path`` directive. Keeping this directive as empty string gives users using full access main Bconsole.

So, summary for this description is:

 - add the API users to ``bacularis.users`` file (ex. by ``htpasswd`` tool)
 - define the same API user names in ``basic.conf``

Please let us know if it helped.

Good luck.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @howels 

I see that you have already found the answer :-) Great.

Thanks.

Best regards,
Marcin Haba (gani)

**Comment by howels** [comment]
Thanks for the thorough explanation!
